### ISSUE TITLE
Implementation Request: Pub Sub

### ISSUE THREAD

**Issue by W-Lawless** [michaelvanstraten/swifty-redis#4]
How do I listen for messages on a channel once subscribed?

**Comment by michaelvanstraten** [comment]
Okay, sadly it's currently not supported. Since streams came out, I did not really focus on pub sub in the implementation. But I will add it to the to-do list, give me a day or two.

**Comment by W-Lawless** [comment]
> Okay, sadly it's currently not supported. Since streams came out, I did not really focus on pub sub in the implementation. But I will add it to the to-do list, give me a day or two.

I'm actually fairly new to Redis and didn't know it had this feature; it may actually be better for my use case! I'm sure the package could use pub/sub for others who come along, but as is, maybe just an example of how to use streams would be enough for short-term?

**Comment by michaelvanstraten** [comment]
Sadly I am very Business this weak so I can't help you with my full availability but from my memory there are two ways of reading from a stream, blocking and non blocking. I thing the Redis documentation Page is pretty up to date so you can check that in the mean time while I update the docs. I think you can just use the already existing implementation of the commands in the package to read from a stream. There are multiple of them, the difference to PubSub ist that you actually get the message as a response to your Command and not as a message some later time after subscribing. 

You can check the Stream Swift file, in the source, for some helper types that make it easer to work with streams.

I am sorry i can't be of more help right now but the Redis documentation should cover most of your questions.

**Comment by michaelvanstraten** [comment]
Okay, sorry for the long wait but the mockup implementation of pub sub is now done, caaf83b.

**Comment by AdieOlami** [comment]
Hey, awesome package. Thanks.

I tried using the pubsub but does not listen to the message.

I have this

protocol RedisManager {
    func connection() async throws -> RedisConnection
    func pubsub() async throws -> PubSubConnection
    func subscribe(connection: PubSubConnection) async throws
    func listen(connection: PubSubConnection) async throws
}

final class DefaultRedisManager: RedisManager {
    
    let client = RedisClient(
        .init("example.com"),
        params: .tcp,
        database: 0
    )
    
    func connection() async throws -> RedisConnection {
        try await client.get_connection()
    }
    
    func pubsub() async throws -> PubSubConnection {
        try await client.get_pub_sub_connection()
    }
    
    func subscribe(connection: PubSubConnection) async throws {
        try await connection.subscribe("notifications:xxxx")
    }
    
    func listen(connection: PubSubConnection) async throws {
        var messages = await connection.messages().makeAsyncIterator()
        
        if let result = await messages.next() {
            switch result {
            case let .success(message):
                print("[PUBSUB] CHANNEL::: \(message.channel)")
                print("[PUBSUB] TYPE::: \(message)")
            case let .failure(error):
                print("[PUBSUB] Received error: \(error)")
            }
        }

    }
}

**Comment by michaelvanstraten** [comment]
To which channel are you publishing?
