### ISSUE TITLE
Raw JSON value truncated using a GET

### ISSUE THREAD

**Issue by fluentindata** [michaelvanstraten/swifty-redis#8]
We are setting a key, value pair (key_string -> value_string) where the value_string is a raw JSON with approximately `1 million` chars. This value is stored correctly on Redis but when fetched using a get it always returns a random amount of chars back (usually between `100k` to `400k`). This is extremely odd.

Also using the `.getrange` method, when setting the start and end range from `0` to `1M`, we are also getting the same behavior. Conversely, when we set the end range to `100` it returns the expected `100` chars.

**Comment by michaelvanstraten** [comment]
This is truly very odd behavior, give me a second I will investigate this.

**Comment by michaelvanstraten** [comment]
Could you give me the hash of the current commit you are on?

**Comment by michaelvanstraten** [comment]
I am having breakfast right now so off the top of my head I would say that it might be too you running other commands on the connection, besides the get, in parallel and those might be interleaving.

**Comment by michaelvanstraten** [comment]
Okay, I think I found the issue

**Comment by michaelvanstraten** [comment]
Fix is ready, just need to document the code changes.

**Comment by bearstacks** [comment]
Thank you so much for fixing this! This really helped my team in getting past an issue we were running into. Really appreciate the quick turnaround 🙏

**Comment by wassup-** [comment]
@michaelvanstraten Thank you for fixing this. I ran into the same problem using the latest SPM release, but when referencing the main branch the problem is solved. 

Can you please create a new SPM release containing the fix?

**Comment by michaelvanstraten** [comment]
> Can you please create a new SPM release containing the fix?

Shure, no problem, should be out by tomorrow.

**Comment by michaelvanstraten** [comment]
@wassup- there are some new tags, check them out.
