### ISSUE TITLE
Binary bulk string support

### ISSUE THREAD

**Issue by fdgogogo** [michaelvanstraten/swifty-redis#9]
Current implementation requires value of a key to be an UTF-8 encoded string

https://github.com/michaelvanstraten/swifty-redis/blob/56ce6d07acda69d151179ea4caa5f0bbd06535b0/Sources/SwiftyRedis/Value.swift#L20-L21

https://github.com/michaelvanstraten/swifty-redis/blob/56ce6d07acda69d151179ea4caa5f0bbd06535b0/Sources/SwiftyRedis/ResponseValueParser.swift#L89-L94

If the value is binary, eg gzipped data, I don't find a way to get the raw data. Please help, thx!

**Comment by michaelvanstraten** [comment]
I'm sorry, you are totally correct. BulkStrings can contain non utf-8 data, i will fix this.

**Comment by michaelvanstraten** [comment]
Okay, quick fix is ready, I will document the changes later.
